### PR TITLE
Fold functions only

### PR DESCRIPTION
**Pull request by zdm**
You can use `let g:pgsql_fold_functions_only = 1` to fold only functions, procedures and "do" blocks.

### CODE REVIEW

**Comment by zdm** [comment]
Aldo you needed to use single quotes or escape `\` in `execute` call. This is fixed in this aptch.

**Comment by lifepillar** [comment]
Thanks! I have fixed the unescaped backslashes. I will review this during the weekend.

**Comment by zdm** [comment]
Hi,
Did you forget about this PR? ;=))

**Comment by lifepillar** [comment]
Sorry for taking so long! Yes, this had fallen off my radar.

Thanks for contributing! 👌

**Pull request merged**
